version: '3.7'
services:
  apdv_backend:
    image: 'apdv-backend'
    build:
      context: .
    ports:
      - "5000:5000"
    container_name: apdv-backend
    depends_on:
      - PostgreSQL

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres:15.1
    container_name: PostgesSQL
    volumes:
      - apdv_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apdv_db
    restart: always

volumes:
  apdv_volume: